# Generated by Django 3.0.4 on 2020-03-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190430_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.SlugField(choices=[('news', 'お知らせ'), ('learn', 'アニメーションの書き方'), ('event', 'イベント'), ('other', 'その他')], default='news', verbose_name='カテゴリ'),
        ),
    ]
