# Generated by Django 3.0.4 on 2020-03-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.SlugField(choices=[('news', 'お知らせ'), ('update', '更新/変更'), ('howto', 'アニメーションの書き方'), ('info', 'サービス情報'), ('event', 'イベント')], default='news', verbose_name='カテゴリ'),
        ),
    ]
