# Generated by Django 2.1.15 on 2020-01-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('upload', '0019_auto_20190928_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_ban',
            field=models.BooleanField(default=False, verbose_name='運営による非公開'),
        ),
    ]
