# Generated by Django 3.0.4 on 2020-04-16 13:13

from django.db import migrations, models
import upload.models
import upload.validators


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0020_video_is_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpurevideo',
            name='file',
            field=models.FileField(upload_to=upload.models.temp_upload_to, validators=[upload.validators.FileValidator(allowed_extensions=['mp4', 'avi', 'gif', 'mov'], max_size=104857600), upload.validators.video_file_validator], verbose_name='動画ファイル'),
        ),
    ]
