version: '3'

volumes:
  db_data:
  venv:
  sock:
  node_modules:

services:
  db:
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password000
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: always

  web:
    build: ./web
    image: mkizka/tsukuriga
    env_file: .env
    volumes:
      - ./web:/code
      - venv:/code/.venv
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - db
      - node
    restart: always

  node:
    image: node:13-alpine
    command: yarn dev
    volumes:
      - ./node:/code
      - ./web/assets:/code/assets
      - node_modules:/code/node_modules
    working_dir: /code
