version: '3'

volumes:
  db_data:
  venv:
  node_modules:

services:
  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log:/var/log/nginx
      - ./nginx/assets:/assets
    depends_on:
      - web

  db:
    image: mysql:5.7
    expose:
      - "3306"
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  web:
    build: ./web
    env_file: .env
    entrypoint: pipenv run
    command: start
    volumes:
      - ./web:/code
      - venv:/code/.venv
      - ./nginx/assets:/assets
    dns:
      - 8.8.8.8
      - 8.8.4.4
    expose:
      - "8001"
    depends_on:
      - db

  node:
    image: node:11.14
    command: bash -c "yarn && yarn run dev"
    volumes:
      - node_modules:/code/node_modules
      - ./node:/code
      - ./web/assets:/code/assets
    working_dir: /code
