version: '3'

volumes:
  venv-prod:
  assets-prod:

services:
  db-prod:
    image: gcr.io/cloudsql-docker/gce-proxy
    command:
      [
        "/cloud_sql_proxy",
        "-instances=$SQL_CONNECTION_NAME=tcp:0.0.0.0:3306",
        "-credential_file=/config/serviceAccountKeys.json"
      ]
    volumes:
      - ./web/serviceAccountKeys.json:/config/serviceAccountKeys.json

  web-prod:
    image: asia.gcr.io/tsukuriga/tsukuriga
    env_file: .env
    volumes:
      - ./web:/code
      - venv-prod:/code/.venv
      - assets-prod:/code/assets
