version: '3'

volumes:
  db_data:
  venv:
  sock:

services:
  db:
    image: mysql:5.7
    expose:
      - "3306"
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: always

  web:
    build: ./web
    image: mkizka/tsukuriga
    env_file: .env
    command: poetry run python manage.py runserver_plus 0.0.0.0:8080
    volumes:
      - ./web:/code
      - venv:/code/.venv
      - ./nginx/assets:/assets
      - sock:/sock
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:8080"
    depends_on:
      - db
      - node
    restart: always

  node:
    image: node
    env_file: .env
    command: python3 entrypoint.py
    volumes:
      - ./node:/code
      - ./web/assets:/code/assets
    working_dir: /code
