# Generated by Django 2.1.15 on 2020-03-13 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('browse', '0014_auto_20200310_0602'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoprofilelabelrelation',
            unique_together=set(),
        ),
    ]
