# Generated by Django 3.0.4 on 2020-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0015_auto_20200313_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='icon',
            field=models.SlugField(default='fas fa-star', verbose_name='アイコン'),
        ),
    ]
