# Generated by Django 3.0.4 on 2020-03-16 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0004_friendship'),
        ('account', '0012_user_contribution_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followees',
            field=models.ManyToManyField(related_name='_user_followees_+', through='ajax.FriendShip', to=settings.AUTH_USER_MODEL, verbose_name='フォロー中のユーザー'),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_user_followers_+', through='ajax.FriendShip', to=settings.AUTH_USER_MODEL, verbose_name='フォローされているユーザー'),
        ),
    ]
