# Generated by Django 3.0.4 on 2020-04-08 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0005_mute'),
        ('account', '0013_auto_20200316_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mutes',
            field=models.ManyToManyField(related_name='_user_mutes_+', through='ajax.Mute', to=settings.AUTH_USER_MODEL, verbose_name='ミュート中のユーザー'),
        ),
    ]
