# https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml

name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - migration/*

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: asia-northeast2
  SERVICE_NAME: tsukuriga-cd-test

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
      - name: yarn install and build
      run: |
        yarn install
        yarn build
        cp -rf assets/bundle ../web/assets/bundle
      working-directory: ./node

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.RUN_SA_EMAIL }}
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      # Configure docker to use the gcloud cli
      - run: gcloud auth configure-docker --quiet

      # Build and push image to Google Container Registry
      - name: Build
        run: |
          docker build -t "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" ./web
          docker push "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      - name: collectstatic and push to CGS
        run: |
          - docker run -e DEBUG=false "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            python manage.py collectstatic --no-input

      # Deploy image to Cloud Run
      - name: Deploy
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
