# https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml

name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      migration/*

env:
  PROJECT_NAME: tsukuriga-pre
  PROJECT_ZONE: us-west1-a
  COMPUTE_NAME: tsukuriga-vm
  RUN_NAME: tsukuriga
  RUN_IMAGE: gcr.io/tsukuriga-pre/tsukuriga:${{ github.sha }}
  RUN_SA_EMAIL: ${{ secrets.RUN_SA_EMAIL }}
  RUN_SA_KEY: ${{ secrets.RUN_SA_KEY }}
  DJANGO_KEY: ${{ secrets.DJANGO_KEY }}
  SQL_CONNECTION_NAME: ${{ secrets.SQL_CONNECTION_NAME }}
  SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
  TWITTER_KEY: ${{ secrets.TWITTER_KEY }}
  TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: 静的ファイルのビルド
        run: |
          cd node
          yarn install
          yarn build
          cp -rf ./assets/* ../web/assets/

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ env.RUN_SA_EMAIL }}
          service_account_key: ${{ env.RUN_SA_KEY }}
          project_id: ${{ env.PROJECT_NAME }}

      - name: Container Registryへのデプロイ
        run: |
          gcloud auth configure-docker --quiet
          docker build -t "$RUN_IMAGE" ./web
          docker push "$RUN_IMAGE"

      - name: Cloud Storageへのデプロイ
        run: |
          RUN_SA_KEY_BASE64=$(echo $RUN_SA_KEY | openssl enc -e -base64)
          docker run \
            -e DEBUG=false \
            -e SECRET_KEY=$DJANGO_KEY \
            -e RUN_SA_KEY_BASE64="$RUN_SA_KEY_BASE64" \
            "$RUN_IMAGE" \
            python manage.py collectstatic --no-input

      - name: Compute Engineへのデプロイ
        run: |
          ENV_CONTENT="
            SECRET_KEY=$DJANGO_KEY
            RUN_IMAGE=$RUN_IMAGE
            RUN_SA_KEY_BASE64=$RUN_SA_KEY_BASE64
            MYSQL_HOST=/cloudsql/$SQL_CONNECTION_NAME
            MYSQL_PORT=
            MYSQL_ROOT_PASSWORD=$SQL_PASSWORD
          "
          echo "$ENV_CONTENT" > .env
          gcloud compute scp $COMPUTE_NAME:/tsukuriga/.env .env
          gcloud compute ssh $COMPUTE_NAME --zone $PROJECT_ZONE \
            --command "
            SCRIPT_PATH=/tsukuriga/scripts/cron.sh
            sudo chmod +x $SCRIPT_PATH
            sudo $SCRIPT_PATH
            "

      - name: Cloud Runへのデプロイ
        run: |
          gcloud run deploy "$RUN_NAME" \
            --quiet \
            --region "$PROJECT_ZONE" \
            --image "$RUN_IMAGE" \
            --update-env-vars "DEBUG=false" \
            --update-env-vars "SECRET_KEY=$DJANGO_KEY" \
            --update-env-vars "ADMIN_MAIL=compeitoon@gmail.com" \
            --update-env-vars "RUN_SA_KEY_BASE64=$RUN_SA_KEY_BASE64" \
            --update-env-vars "MYSQL_HOST=/cloudsql/$SQL_CONNECTION_NAME" \
            --update-env-vars "MYSQL_PORT=" \
            --update-env-vars "MYSQL_ROOT_PASSWORD=$SQL_PASSWORD" \
            --update-env-vars "TWITTER_KEY=$TWITTER_KEY" \
            --update-env-vars "TWITTER_SECRET=$TWITTER_SECRET" \
            --update-env-vars "EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD" \
            --update-env-vars "INSTANCE-CONNECTION-NAME=$SQL_CONNECTION_NAME" \
            --add-cloudsql-instances "$SQL_CONNECTION_NAME" \
            --platform "managed" \
            --allow-unauthenticated
